#
# This file is part of GEO Knowledge Hub.
# Copyright 2020 GEO Secretariat.
#
# GEO Knowledge Hub is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/geo-knowledge-hub

hooks:

  ApplicationStop:
    - location: scripts/aws_app_stop.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/aws_before_install.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/aws_after_install.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/aws_app_start.sh
      timeout: 1200
      runas: ubuntu
